pipeline {
    agent any
    
    tools {
        maven "MAVEN3"
        jdk "JDK17"
    }

    environment {
        SNAPREPO = 'vprofile-snapshot'
		NEXUSUSER = 'admin'
		NEXUSPASS = 'admin'
		RELEASEREPO = 'vprofile-release'
		CENTRALREPO = 'vpro-maven-central'
		NEXUSIP = '172.31.47.168'
		NEXUSPORT = '8081'
		NEXUSGRP_REPO = 'vpro-maven-group'
        NEXUSLOGIN = 'nexuslogin'
        SONARSERVER = 'sonarserver'
        SONARSCANNER = 'sonarscanner'
    }


    stages {
        stage('Install'){
            steps {
                sh 'mvn -s settings.xml clean install'
            }
        }
        stage('Test'){
            steps {
                sh 'mvn -s settings.xml test'
            }
        }

        stage('Checkstyle Analysis'){
            steps {
                sh 'mvn -s settings.xml checkstyle:checkstyle'
            }
        }

        stage('Upload Reports To SonarQube'){
            environment {
                scannerHome = tool "${SONARSCANNER}"
            }
            steps {
                withSonarQubeEnv("${SONARSERVER}") {

                    sh "${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=vprofile \
                        -Dsonar.java.binaries=target \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.java.sources=src/main/java \
                        -Dsonar.exclusions=**/target/**/*,**/webapp/**/*,**/entity/* \
                        -Dsonar.jacoco.reportPath=target/jacoco.exec \
                        -Dsonar.junit.reportsPath=target/surefire-reports \
                        -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
                        -Dsonar.host.url=http://172.31.45.194"
                }
            }
        }
        stage("Quality Gate") {
            steps {
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
        }

        stage("Upload Artifact"){
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: "${NEXUSIP}" + ":" + "${NEXUSPORT}",
                    groupId: 'com.example',
                    version: "${BUILD_TIMESTAMP}",
                    repository: "${RELEASEREPO}",
                    credentialsId: "${NEXUSLOGIN}",
                    artifacts: [
                        [artifactId: 'vprofile',
                         classifier: '',
                         file: 'target/vprofile-v2.war',
                         type: 'war']
                    ]
                )    
            }
        }
    }
}