pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "JDK17"
    }

    environment {
        SNAP_REPO = 'vprofile-snapshot'
		NEXUS_USER = 'admin'
		NEXUS_PASS = 'admin'
		RELEASE_REPO = 'vprofile-release'
		CENTRAL_REPO = 'vpro-maven-central'
		NEXUSIP = '172.31.47.168'
		NEXUSPORT = '8081'
		NEXUS_GRP_REPO = 'vpro-maven-group'
        NEXUS_LOGIN = 'nexuslogin'
        SONAR_SERVER = 'sonarserver'
        SONAR_SCANNER = 'sonarscanner'
    }

    stages {
        stage('Install'){
            steps {
                sh 'mvn -s settings.xml -DskipTests install'
            }
        }
        stage('Test'){
            steps {
                sh 'mvn -s settings.xml test'
            }
        }

        stage('Checkstyle Analysis'){
            steps {
                sh 'mvn -s settings.xml checkstyle:checkstyle'
            }
        }

        stage('Upload Reports To SonarQube'){
            environment {
                scannerHome = tool "${SONAR_SCANNER}"
            }
            steps {
                withSonarQubeEnv("${SONAR_SERVER}") {

                    sh "${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=vprofile \
                        -Dsonar.java.binaries=target \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.java.sources=src/main/java \
                        -Dsonar.exclusions=**/target/**/*,**/webapp/**/*,**/entity/* \
                        -Dsonar.jacoco.reportPath=target/jacoco.exec \
                        -Dsonar.junit.reportsPath=target/surefire-reports \
                        -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
                        -Dsonar.host.url=http://172.31.45.194"
                }
            }
        }
        stage('Quality Gate') {
            steps {
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
        }

        stage('Upload Artifact'){
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: "${NEXUSIP}" + ":" + "${NEXUSPORT}",
                    groupId: 'com.example',
                    version: "${BUILD_TIMESTAMP}",
                    repository: "${RELEASE_REPO}",
                    credentialsId: "${NEXUS_LOGIN}",
                    artifacts: [
                        [artifactId: 'vprofile',
                         classifier: '',
                         file: 'target/vprofile-v2.war',
                         type: 'war']
                    ]
                )    
            }
        }

        /*stage('Build Docker Image'){
            steps {
                sh "docker image build -t vpro-app:${env.BUILD_ID} Docker-files/app/multistage/"
            }
        }*/

        stage('Push Docker Image to ECR'){
            steps {
                script{
                    docker.withRegistry('https://138913568231.dkr.ecr.us-east-1.amazonaws.com/vprofile','ecr:us-east-1:awslogin'){
                        docker.build("vpro-app:${env.BUILD_ID}", "./Docker-files/app/multistage/").push
                    }
                }
            }
        }
    }
}